### ISSUE TITLE
Add Logout - Not Listed on Mockup Page

### ISSUE THREAD

**Issue by egh2493** [nickydraz/mockups#1]
To Do: 
Add a logout link to each page.
I think it would look nice next to the About link at the bottom, but from a UX POV it would probably be better if it were at the top, maybe under Accounts or in its own tab.

**Comment by nickydraz** [comment]
It should be somewhere that is easy/logical for the user to look. I'm almost tempted to agree to make it its own tab

**Comment by nickydraz** [comment]
Added this under the 'Accounts' pill on the navbar, as was requested by Krieger
