### ISSUE TITLE
Comments Throughout

### ISSUE THREAD

**Issue by nickydraz** [nickydraz/mockups#3]
Once we have most of the big work done, we should begin adding some comments throughout. Would help the Ruby folks once we start to transition to ERB files. Might save us some time and effort, as they'll have to ask us less about what a div is doing before they modify it for Ruby.

**Comment by egh2493** [comment]
Like he said, it would be helpful too on the custom CSS page especially when they're creating dynamic tables and what not so they know which styles to use where.

**Comment by nickydraz** [comment]
Absolutely.
