### ISSUE TITLE
Ruby on Rails Conversion

### ISSUE THREAD

**Issue by nickydraz** [nickydraz/mockups#5]
We kin of need to begin this process.... Most of it should be easy, but the links/routes are going to be a pain in the keister... As is the application_layout file...

**Comment by egh2493** [comment]
Will need to wait until the backend folks get started on creating the project

**Comment by nickydraz** [comment]
Guess we should ask him who is creating the project. At the least, once it's made we can throw our files in there. Then the other folks can worry about the routes, potentially.

**Comment by egh2493** [comment]
Maybe, I'm sure he'll talk about that today after the presentations.

**Comment by nickydraz** [comment]
Here's hoping. If he doesn't we should bring it up. Best to get it addressed now rather than next week.

**Comment by egh2493** [comment]
Right. If we’re beginning work on code today though, we’d better talk about it...

**Comment by nickydraz** [comment]
Yeah...

**Comment by nickydraz** [comment]
Have converted the pages. Waiting until after the product demo to add newer changes to the ERB files. Closing the issue.
